from expired_cert_finder.defaults import EXPIRY_WINDOW, EXPIRED_CERT_LIST_FILENAME, ALLOWED_LIST_FILENAME

STRIP_WIDTH = 130
STRIP_CHAR = '-'

BANNER = """
                       _               __                  __     _____           __         
      ___  _  ______  (_)_______  ____/ /  ________  _____/ /_   / __(_)___  ____/ /__  _____
     / _ \| |/_/ __ \/ / ___/ _ \/ __  /  / ___/ _ \/ ___/ __/  / /_/ / __ \/ __  / _ \/ ___/
    /  __/>  </ /_/ / / /  /  __/ /_/ /  / /__/  __/ /  / /_   / __/ / / / / /_/ /  __/ /    
    \___/_/|_/ .___/_/_/   \___/\__,_/   \___/\___/_/   \__/  /_/ /_/_/ /_/\__,_/\___/_/     
            /_/
"""

HELP_TEXT = """
Usage:
    single file: expired-cert-finder flags file_with_certificates_in.txt
    directory: expired-cert-finder flags
"""

HELP_FLAG = """
Flags:
  --help                       : Show this text
  --debug                      : (bool) Adds extra logging (Default: False)
  --slack                      : (bool) Send results to Slack (Default: False)
  --ui=False                   : (bool) Do not show the progress bar (Default: True)
  --save-results               : (bool) Save the results to a file (Default: False)
  --expired-only               : (bool) Only show expired certificates (Default: False)
  --expiry-window              : (Number) Window for expiring certificates (Default: {EXPIRY_WINDOW})
  --expired-cert-list-filename : (Filename) Where to save list of expiring/expired certificates (Default: {EXPIRED_CERT_LIST_FILENAME}) 
  --slack-webhook-url          : (URL) This is the webhook url generated by Slack e.g https://hooks.slack.com/services/...
  --allowed-list               : (Filename) Path for allowed expiring/expired certificates (Default: {ALLOWED_LIST_FILENAME})
"""\
    .replace("{EXPIRY_WINDOW}",str(EXPIRY_WINDOW))\
    .replace("{EXPIRED_CERT_LIST_FILENAME}", EXPIRED_CERT_LIST_FILENAME)\
    .replace("{ALLOWED_LIST_FILENAME}", ALLOWED_LIST_FILENAME)

def print_stripe(new_line=False):
    for i in range(0, STRIP_WIDTH):
        print(STRIP_CHAR, end='')

    if new_line:
        print('\n')

def print_help():
    print(BANNER)
    print_stripe()
    print(HELP_TEXT)
    print_stripe()
    print(HELP_FLAG)